title: 大反派
email: cbtpro@163.com
description: '去你所能到达的最远处,等你到那儿,你会看得更远。Go as far as you can see; when you get there, you’ll be able to see farther.'
baseurl: ''
url: ''
twitter_username: cbtpro
github_username: cbtpro
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "assets/img"
    values:
      layout: post
      title: "未命名"
      author: cbtpro
      image: true
